CREATE TABLE IF NOT EXISTS displays (
	id        INTEGER PRIMARY KEY AUTOINCREMENT,
	name      TEXT    NOT NULL UNIQUE,
	mirror_of TEXT    NOT NULL DEFAULT '',
	video     INTEGER NOT NULL DEFAULT 0,
	timer     INTEGER NOT NULL DEFAULT 60,
	seed      INTEGER NOT NULL DEFAULT 0,
	width     INTEGER NOT NULL DEFAULT 0,
	height    INTEGER NOT NULL DEFAULT 0,
	theme     INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS libraries (
	id     INTEGER PRIMARY KEY AUTOINCREMENT,
	path   TEXT    NOT NULL UNIQUE,
	thumbs TEXT    NOT NULL DEFAULT '[]',
	images INTEGER NOT NULL DEFAULT 0,
	videos INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS status (
	id         INTEGER PRIMARY KEY CHECK (id = 1),
	mpvpaper   INTEGER NOT NULL DEFAULT 0,
	hyprpaper  INTEGER NOT NULL DEFAULT 0,
	video      TEXT    NOT NULL DEFAULT '',
	image      TEXT    NOT NULL DEFAULT '',
	color      TEXT    NOT NULL DEFAULT '#ff0000',
	label      TEXT    NOT NULL DEFAULT 'Loading...',
	connected  INTEGER NOT NULL DEFAULT 0,
	updated_at TEXT    NOT NULL DEFAULT (datetime('now'))
);
